{% set name = "autogluon.tabular" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: 96075e9bfce79420fe78a5566a1ba82f9a80598e955f4a4fc490f5561ede70bd
  # Use the latest commit temporarily
  url: https://github.com/autogluon/autogluon/archive/e6458bdbbaa22908457a199f1095b80edc3b85f9.tar.gz
  sha256: 39e542cfc5f7d5ba767dbb20fa462d9a7d535115011b3cd2e98dd70175090722

build:
  # noarch: python
  skip: True  # [py>=311]
  number: 0
  script: {{ PYTHON }} -m pip install ./tabular -vv
  script_env:
   - RELEASE=1

requirements:
  build:
    - {{ compiler('cuda') }}                 # [linux and cuda_compiler_version != "None"]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  >=1.21,<1.27                    # [build_platform != target_platform]
  host:
    - python # >=3.8,<3.11
    - pip
  run:
    - python # >=3.8,<3.11
    - numpy >=1.21,<1.27  
    - scipy >=1.5.4,<1.12
    - pandas >=1.4.1,<1.6
    - scikit-learn >=1.0,<1.3
    - networkx >=2.3,<3.0
    - pytorch <1.13,>=1.9  # [not win]
    - lightgbm >=3.3,<3.4
    - xgboost >=1.6,<1.8
    - catboost >=1.0,<1.2 
    - fastai >=2.3.1,<2.8  # [not win]   
    - autogluon.core =={{ version }}
    - autogluon.features =={{ version }}

test:
  imports:
    - autogluon.tabular
  commands:
    - python -c "from autogluon.tabular import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip
    - pytorch =*=cuda*  # [linux and cuda_compiler_version != "None"]

about:
  home: https://pypi.org/project/autogluon.tabular
  summary: AutoML for Image, Text, and Tabular Data
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
    - Innixma
