{% set name = "autogluon.tabular" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fd388cb91e5a9467252be061b1bb90c9735d7f543d1d8335ff75f4b362ce4d86

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install ./tabular -vv
  script_env:
    - RELEASE=1

requirements:
  build:
    # - {{ compiler('cuda') }}                 # [linux and cuda_compiler_version != "None"]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  >=1.25.0,<2.3.0                 # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - pip
  run:
  # see deps in https://github.com/autogluon/autogluon/blob/master/tabular/setup.py
  # dep versions defined in https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py
    - python >={{ python_min }},<3.13
    - numpy >=1.25.0,<2.3.0
    - scipy >=1.5.4,<1.16
    - pandas >=2.0.0,<2.3.0
    - pytorch >=2.2,<2.7   # pin lowerbound to 2.2 to avoid dependency resolution issue
    - scikit-learn >=1.4.0,<1.7
    - networkx >=3.0,<4
    - autogluon.core =={{ version }}
    - autogluon.features =={{ version }}
    - lightgbm >=4.0,<4.7
    - catboost >=1.2.6,<1.3
    - xgboost >=2.0,<3.1
    - fastai >=2.3.1,<2.9

test:
  imports:
    - autogluon.tabular
  commands:
    - python -c "from autogluon.tabular import __version__ as v; from packaging.version import parse; expected = '{{ version }}'; assert parse(v) == parse(expected), f'{v} != {expected}'"
  requires:
    - pip
    # - pytorch =*=cuda*  # [linux and cuda_compiler_version != "None"]

about:
  home: https://pypi.org/project/autogluon.tabular
  summary: AutoML for Image, Text, and Tabular Data
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tonyhoo
    - suzhoum
    - Innixma
    - prateekdesai04
