{% set name = "autogluon.tabular" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/6af92e149491f6e5062495d87306b3625d12d992.tar.gz
  sha256: a55be8adcd361c1c75275205783a0563d0aef684bb23ea78e563c05bbf094969

build:
  noarch: python
  # skip: true  # [py>=311]
  number: 1
  script: {{ PYTHON }} -m pip install ./tabular -vv
  script_env:
    - RELEASE=1

requirements:
  build:
    # - {{ compiler('cuda') }}                 # [linux and cuda_compiler_version != "None"]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  >=1.21,<1.27                    # [build_platform != target_platform]
  host:
    - python >=3.8,<3.11
    - pip
  run:
  # see deps in https://github.com/autogluon/autogluon/blob/master/tabular/setup.py
  # dep versions defined in https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py
    - python >=3.8,<3.11
    - numpy >=1.21,<1.27
    - scipy >=1.5.4,<1.12
    - pandas >=1.4.1,<1.6
    - scikit-learn >=1.0,<1.3
    - networkx >=3.0,<4
    - pytorch >=2.0,<2.1
    - lightgbm >=3.3,<3.4
    - xgboost >=1.6,<1.8
    - catboost >=1.1,<1.3
    - fastai >=2.3.1,<2.8
    - autogluon.core =={{ version }}
    - autogluon.features =={{ version }}

test:
  imports:
    - autogluon.tabular
  commands:
    # Temporarily disable for 0.8.2 patching
    # - python -c "from autogluon.tabular import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip
    # - pytorch =*=cuda*  # [linux and cuda_compiler_version != "None"]

about:
  home: https://pypi.org/project/autogluon.tabular
  summary: AutoML for Image, Text, and Tabular Data
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yinweisu
    - giswqs
    - Innixma
