{% set name = "autogluon.tabular" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://autogluon.s3.us-west-2.amazonaws.com/tarballs/0.8.3_patch/tarball.tar.gz
  sha256: 1ccc6834b753ad0dc1d96338d8d56ada5b86356a2d34a9e2a29c3e685af277e1

build:
  noarch: python
  # skip: true  # [py>=311]
  number: 2
  script: {{ PYTHON }} -m pip install ./tabular -vv
  script_env:
    - RELEASE=1

requirements:
  build:
    # - {{ compiler('cuda') }}                 # [linux and cuda_compiler_version != "None"]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  >=1.21,<1.27                    # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - pip
  run:
  # see deps in https://github.com/autogluon/autogluon/blob/master/tabular/setup.py
  # dep versions defined in https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py
    - python >={{ python_min }},<3.11
    - numpy >=1.21,<1.27
    - scipy >=1.5.4,<1.12
    - pandas >=1.4.1,<2.2
    - scikit-learn >=1.1,<1.5
    - networkx >=3.0,<4
    - pytorch >=1.13,<2.1
    - lightgbm >=3.3,<3.4
    - xgboost >=1.6,<1.8
    - catboost >=1.1,<1.3
    - fastai >=2.3.1,<2.8
    - autogluon.core =={{ version }}
    - autogluon.features =={{ version }}

test:
  imports:
    - autogluon.tabular
  commands:
    - python -c "from autogluon.tabular import __version__ as v; from packaging.version import parse; expected = '{{ version }}'; assert parse(v) == parse(expected), f'{v} != {expected}'" 
  requires:
    - pip
    # - pytorch =*=cuda*  # [linux and cuda_compiler_version != "None"]
    - python {{ python_min }}

about:
  home: https://pypi.org/project/autogluon.tabular
  summary: AutoML for Image, Text, and Tabular Data
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tonyhoo
    - suzhoum
    - giswqs
    - Innixma
    - prateekdesai04
