{% set name = "autogluon.tabular" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz 
  sha256: a4d950b5c796a835c690d25dc2406ab35062a973ed70685f5b8f1e850b780bbc 

build:
  noarch: python
  # skip: true  # [py>=311]
  number: 1
  script: {{ PYTHON }} -m pip install ./tabular -vv
  script_env:
    - RELEASE=1

requirements:
  build:
    # - {{ compiler('cuda') }}                 # [linux and cuda_compiler_version != "None"]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  >=1.21,<1.29                    # [build_platform != target_platform]
  host:
    - python >=3.8,<3.12
    - pip
  run:
  # see deps in https://github.com/autogluon/autogluon/blob/master/tabular/setup.py
  # dep versions defined in https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py
    - python >=3.8,<3.12
    - numpy >=1.21,<1.29
    - scipy >=1.5.4,<1.13
    - pandas >=2.0.0,<2.2.0
    - scikit-learn >=1.3.0,<1.5
    - networkx >=3.0,<4
    - pytorch >=2.0,<2.1
    - lightgbm >=3.3,<4.2
    - xgboost >=1.6,<1.8
    - catboost >=1.1,<1.2  # [osx and python_version < '3.11']
    - catboost >=1.1,<1.3  # [not osx]
    - fastai >=2.3.1,<2.8
    - autogluon.core =={{ version }}
    - autogluon.features =={{ version }}

test:
  imports:
    - autogluon.tabular
  commands:
    - python -c "from autogluon.tabular import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip
    # - pytorch =*=cuda*  # [linux and cuda_compiler_version != "None"]

about:
  home: https://pypi.org/project/autogluon.tabular
  summary: AutoML for Image, Text, and Tabular Data
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tonyhoo
    - suzhoum
    - yinweisu
    - giswqs
    - Innixma
